version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11.4
    steps:
      - checkout # check out the code in the project directory
      - setup_remote_docker # install docker in docker
      - run:
          name: Prepare Environment
          command: |
            cp conf/sower.toml .
            cp deploy/* .
            mkdir artifacts
      - run:
          name: build linux Binary
          command: |
            make build
            tar czvf artifacts/sower-linux.tar.gz sower sower.toml
      - run:
          name: build macOS Binary
          command: |
            GOOS=darwin GOARCH=amd64 make build
            tar czvf artifacts/sower-darwin.tar.gz sower sower.toml
      - run:
          name: build Windows Binary
          command: |
            GOOS=windows GOARCH=amd64 make build
            tar czvf artifacts/sower-windows.tar.gz sower sower.toml
      - run:
          name: Publish Release on GitHub
          command: |
            if git log -1 --pretty='%s' | grep -oE '(^|\s)@release(\s|$)'; then
              go get github.com/tcnksm/ghr
              VERSION=$(git describe --tags)
              ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION%-*-*} artifacts/
            fi
      - run:
          name: build docker image
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            make image
            VERSION=$(git describe --tags)
            docker tag wweir/sower:latest wweir/sower:${VERSION%-*-*}
            docker push wweir/sower:${VERSION%-*-*}
            docker push wweir/sower:latest