version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11.4
    steps:
      - checkout # check out the code in the project directory
      - setup_remote_docker # install docker in docker
      - run:
          name: Prepare Environment
          command: |
            cp conf/sower.toml .
            cp deploy/* .
            mkdir artifacts
      - run:
          name: build linux Binary
          command: |
            make build
            tar czvf artifacts/sower_linux_amd64.tar.gz sower sower.toml sower-client.service sower-server.service
      - run:
          name: build macOS Binary
          command: |
            GOOS=darwin GOARCH=amd64 make build
            tar czvf artifacts/sower_darwin_amd64.tar.gz sower sower.toml cc.wweir.sower.plist
      - run:
          name: build Windows Binary
          command: |
            GOOS=windows GOARCH=amd64 make build
            tar czvf artifacts/sower_windows_amd64.tar.gz sower sower.toml
      - run:
          name: Publish Release on GitHub
          command: |
            if git log -1 --pretty='%s' | grep -oE '(^|\s)@release(\s|$)'; then
              GHR_VERSION="$(curl -s "https://api.github.com/repos/tcnksm/ghr/releases/latest" | awk -F '"'  '/tag_name/{printf $4}')"
              curl -SLf https://github.com/tcnksm/ghr/releases/download/"$GHR_VERSION"/ghr_"$GHR_VERSION"_linux_amd64.tar.gz | tar xzC /go/bin --strip-components=1

              VERSION=$(git describe --tags)
              ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION%-*-*} artifacts/
            fi
      - run:
          name: build docker image
          command: |
            if git log -1 --pretty='%s' | grep -oE '(^|\s)@release(\s|$)'; then
              docker login -u $DOCKER_USER -p $DOCKER_PASS
              make image
              VERSION=$(git describe --tags)
              docker tag sower wweir/sower:${VERSION%-*-*}
              docker push wweir/sower:${VERSION%-*-*}
              docker tag sower wweir/sower:latest
              docker push wweir/sower:latest
            fi