net_type="TCP"
cipher="AES_128_GCM"
password="12345678"
server_port="5533"
# server_addr="remote-server:5533" # replce it to remote server
http_proxy=":8080"               # eg: 192.168.0.2:8080
dns_server="223.5.5.5"           # Alibaba public dns
client_ip="127.0.0.1"
# clear_dns_cache="killall -HUP mDNSResponder"
blocklist=[
    "*.google.com", # google
    "*.goo.gl",
    "*.googleusercontent.com",
    "*.googleapis.com",
    "*.youtube.com", # youtube
    "*.ytimg.com",
    "*.ggpht.com",
    "*.googlevideo.com",
    "*.facebook.com", # facebook
    "*.xx.fbcdn.net",
    "*.twitter.com", # twitter
    "*.twimg.com",
    "*.blogspot.com", # blogspot
    "*.wikipedia.org", # wikipeida
    "*.wikimedia.org",
    "*.wikisource.org",
    "*.web.telegram.org", # telegram
    "*.github.com", # github is too slow in direct connection
    "*.github.io",
    "*.s3.amazonaws.com", # aws s3, for github release file
    "*.cloudfront.net",
    "lookup-api.apple.com", # macOS lookup service
    "lookup-api.apple.com.edgekey.net",
    "e16991.b.akamaiedge.net",
]
verbose=0
